#!/bin/sh

set -e

# Use update-alternatives to set proper binary names
update-alternatives --install /usr/bin/man man /usr/bin/mman 100 \
	--slave /usr/bin/apropos apropos /usr/bin/mapropos \
	--slave /usr/bin/soelim soelim /usr/bin/msoelim \
	--slave /usr/bin/whatis whatis /usr/bin/mwhatis \
	--slave /usr/sbin/catman catman /usr/sbin/mcatman
