#!/bin/sh

set -e

# Symlinks. Note: tried to use update-alternatives, didn't work.
ln -sf /usr/bin/man /usr/bin/mman
ln -sf /usr/bin/apropos /usr/bin/mapropos
ln -sf /usr/bin/whatis /usr/bin/mwhatis
ln -sf /usr/bin/soelim /usr/bin/msoelim
ln -sf /usr/sbin/catman /usr/sbin/mcatman
